<?xml version="1.0"?>
<!DOCTYPE ARG[
<!ELEMENT ARG (PREM*, CONC)>
<!ELEMENT PREM (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI)>
<!ELEMENT CONC (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI)>
<!ELEMENT VAR (#PCDATA)>
<!ELEMENT LNOM (#PCDATA)>
<!ELEMENT PRED (#PCDATA)>
<!ELEMENT LPRED (PRED, (VAR*|LNOM*), (VAR*|LNOM*))>
<!ELEMENT COND (ANT,CONS)>
<!ELEMENT BIC (PRIM,SEG)>
<!ELEMENT DISJ (PRIM,SEG)>
<!ELEMENT CONJ (PRIM,SEG)>
<!ELEMENT ANT (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI)>
<!ELEMENT CONS (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI)>
<!ELEMENT PRIM (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI)>
<!ELEMENT SEG (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI)>
<!ELEMENT UNI (VAR, (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI))>
<!ELEMENT EXI (VAR, (LPRED|COND|DISJ|CONJ|BIC|UNI|EXI))>
<!ATTLIST LPRED ID CDATA #IMPLIED>
<!ATTLIST LPRED NEG CDATA #IMPLIED>
<!ATTLIST COND ID CDATA #IMPLIED>
<!ATTLIST COND NEG CDATA #IMPLIED>
<!ATTLIST BIC ID CDATA #IMPLIED>
<!ATTLIST BIC NEG CDATA #IMPLIED>
<!ATTLIST CONJ ID CDATA #IMPLIED>
<!ATTLIST CONJ NEG CDATA #IMPLIED>
<!ATTLIST DISJ ID CDATA #IMPLIED>
<!ATTLIST DISJ NEG CDATA #IMPLIED>
<!ATTLIST UNI ID CDATA #IMPLIED>
<!ATTLIST UNI NEG CDATA #IMPLIED>
<!ATTLIST EXI ID CDATA #IMPLIED>
<!ATTLIST EXI NEG CDATA #IMPLIED>
]>
<!-- P -> Q, P Portanto ~Q -->
<ARG>
     <PREM>
     	<COND ID="0" NEG="">
     		<ANT>
     			<LPRED  ID="1" NEG="">
     				<PRED>P</PRED>
     			</LPRED>
     		</ANT>
     		<CONS>
     			<LPRED  ID="2" NEG="">
     				<PRED>Q</PRED>
     			</LPRED>
     		</CONS>
     	</COND>
     </PREM>
     <PREM>
     	<LPRED ID="3" NEG="">
     		<PRED>P</PRED>
     	</LPRED>
     </PREM>
     <CONC>
     	<LPRED  ID="4" NEG="~">
     		<PRED>Q</PRED>
     	</LPRED>     
     </CONC>
</ARG> 